// This file is auto-generated by @hey-api/openapi-ts

export const AccidentDataSchema = {
  properties: {
    year: {
      type: "integer",
      title: "Year",
    },
    total_accidents: {
      anyOf: [
        {
          type: "integer",
        },
        {
          type: "null",
        },
      ],
      title: "Total Accidents",
    },
    total_killed: {
      anyOf: [
        {
          type: "integer",
        },
        {
          type: "null",
        },
      ],
      title: "Total Killed",
    },
    total_injured: {
      anyOf: [
        {
          type: "integer",
        },
        {
          type: "null",
        },
      ],
      title: "Total Injured",
    },
    daily_deaths: {
      anyOf: [
        {
          additionalProperties: {
            type: "integer",
          },
          type: "object",
        },
        {
          type: "null",
        },
      ],
      title: "Daily Deaths",
    },
    daily_injured: {
      anyOf: [
        {
          additionalProperties: {
            type: "integer",
          },
          type: "object",
        },
        {
          type: "null",
        },
      ],
      title: "Daily Injured",
    },
    monthly_deaths: {
      anyOf: [
        {
          additionalProperties: {
            type: "integer",
          },
          type: "object",
        },
        {
          type: "null",
        },
      ],
      title: "Monthly Deaths",
    },
    monthly_injured: {
      anyOf: [
        {
          additionalProperties: {
            type: "integer",
          },
          type: "object",
        },
        {
          type: "null",
        },
      ],
      title: "Monthly Injured",
    },
    accident_hotspot: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Accident Hotspot",
    },
    vehicles_involved: {
      anyOf: [
        {
          additionalProperties: {
            type: "integer",
          },
          type: "object",
        },
        {
          type: "null",
        },
      ],
      title: "Vehicles Involved",
    },
    date: {
      type: "null",
      title: "Date",
    },
    accidents_by_district: {
      anyOf: [
        {
          additionalProperties: {
            type: "integer",
          },
          type: "object",
        },
        {
          type: "null",
        },
      ],
      title: "Accidents By District",
    },
    id: {
      type: "integer",
      title: "Id",
    },
    created_at: {
      type: "string",
      format: "date-time",
      title: "Created At",
    },
    last_updated: {
      anyOf: [
        {
          type: "string",
          format: "date-time",
        },
        {
          type: "null",
        },
      ],
      title: "Last Updated",
    },
  },
  type: "object",
  required: ["year", "id", "created_at", "last_updated"],
  title: "AccidentData",
} as const;

export const AccidentDataCreateSchema = {
  properties: {
    year: {
      type: "integer",
      title: "Year",
    },
    total_accidents: {
      anyOf: [
        {
          type: "integer",
        },
        {
          type: "null",
        },
      ],
      title: "Total Accidents",
    },
    total_killed: {
      anyOf: [
        {
          type: "integer",
        },
        {
          type: "null",
        },
      ],
      title: "Total Killed",
    },
    total_injured: {
      anyOf: [
        {
          type: "integer",
        },
        {
          type: "null",
        },
      ],
      title: "Total Injured",
    },
    daily_deaths: {
      anyOf: [
        {
          additionalProperties: {
            type: "integer",
          },
          type: "object",
        },
        {
          type: "null",
        },
      ],
      title: "Daily Deaths",
    },
    daily_injured: {
      anyOf: [
        {
          additionalProperties: {
            type: "integer",
          },
          type: "object",
        },
        {
          type: "null",
        },
      ],
      title: "Daily Injured",
    },
    monthly_deaths: {
      anyOf: [
        {
          additionalProperties: {
            type: "integer",
          },
          type: "object",
        },
        {
          type: "null",
        },
      ],
      title: "Monthly Deaths",
    },
    monthly_injured: {
      anyOf: [
        {
          additionalProperties: {
            type: "integer",
          },
          type: "object",
        },
        {
          type: "null",
        },
      ],
      title: "Monthly Injured",
    },
    accident_hotspot: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Accident Hotspot",
    },
    vehicles_involved: {
      anyOf: [
        {
          additionalProperties: {
            type: "integer",
          },
          type: "object",
        },
        {
          type: "null",
        },
      ],
      title: "Vehicles Involved",
    },
    date: {
      type: "null",
      title: "Date",
    },
    accidents_by_district: {
      anyOf: [
        {
          additionalProperties: {
            type: "integer",
          },
          type: "object",
        },
        {
          type: "null",
        },
      ],
      title: "Accidents By District",
    },
  },
  type: "object",
  required: ["year"],
  title: "AccidentDataCreate",
} as const;

export const AccidentDataUpdateSchema = {
  properties: {
    year: {
      anyOf: [
        {
          type: "integer",
        },
        {
          type: "null",
        },
      ],
      title: "Year",
    },
    total_accidents: {
      anyOf: [
        {
          type: "integer",
        },
        {
          type: "null",
        },
      ],
      title: "Total Accidents",
    },
    total_killed: {
      anyOf: [
        {
          type: "integer",
        },
        {
          type: "null",
        },
      ],
      title: "Total Killed",
    },
    total_injured: {
      anyOf: [
        {
          type: "integer",
        },
        {
          type: "null",
        },
      ],
      title: "Total Injured",
    },
    daily_deaths: {
      anyOf: [
        {
          additionalProperties: {
            type: "integer",
          },
          type: "object",
        },
        {
          type: "null",
        },
      ],
      title: "Daily Deaths",
    },
    daily_injured: {
      anyOf: [
        {
          additionalProperties: {
            type: "integer",
          },
          type: "object",
        },
        {
          type: "null",
        },
      ],
      title: "Daily Injured",
    },
    monthly_deaths: {
      anyOf: [
        {
          additionalProperties: {
            type: "integer",
          },
          type: "object",
        },
        {
          type: "null",
        },
      ],
      title: "Monthly Deaths",
    },
    monthly_injured: {
      anyOf: [
        {
          additionalProperties: {
            type: "integer",
          },
          type: "object",
        },
        {
          type: "null",
        },
      ],
      title: "Monthly Injured",
    },
    accident_hotspot: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Accident Hotspot",
    },
    vehicles_involved: {
      anyOf: [
        {
          additionalProperties: {
            type: "integer",
          },
          type: "object",
        },
        {
          type: "null",
        },
      ],
      title: "Vehicles Involved",
    },
    date: {
      type: "null",
      title: "Date",
    },
    accidents_by_district: {
      anyOf: [
        {
          additionalProperties: {
            type: "integer",
          },
          type: "object",
        },
        {
          type: "null",
        },
      ],
      title: "Accidents By District",
    },
  },
  type: "object",
  title: "AccidentDataUpdate",
} as const;

export const AccidentScrapingResponseSchema = {
  properties: {
    message: {
      type: "string",
      title: "Message",
    },
    scraping_completed: {
      type: "boolean",
      title: "Scraping Completed",
    },
    summary: {
      anyOf: [
        {
          additionalProperties: true,
          type: "object",
        },
        {
          type: "null",
        },
      ],
      title: "Summary",
    },
    scraping_error: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Scraping Error",
    },
  },
  type: "object",
  required: ["message", "scraping_completed"],
  title: "AccidentScrapingResponse",
  description: "Response schema for accident scraping endpoint",
} as const;

export const AllAccidentsDataSchema = {
  properties: {
    newsCategory: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Newscategory",
    },
    id: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Id",
    },
    numberOfAccidentsOccured: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Numberofaccidentsoccured",
    },
    isTheAccidentDataYearlyMonthlyOrDaily: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Istheaccidentdatayearlymonthlyordaily",
    },
    dayOfTheWeekOfTheAccident: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Dayoftheweekoftheaccident",
    },
    exactLocationOfAccident: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Exactlocationofaccident",
    },
    areaOfAccident: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Areaofaccident",
    },
    divisionOfAccident: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Divisionofaccident",
    },
    districtOfAccident: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Districtofaccident",
    },
    subdistrictOrUpazilaOfAccident: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Subdistrictorupazilaofaccident",
    },
    isPlaceOfAccidentHighwayOrExpresswayOrWaterOrOthers: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Isplaceofaccidenthighwayorexpresswayorwaterorothers",
    },
    isCountryBangladeshOrOtherCountry: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Iscountrybangladeshorothercountry",
    },
    accidentType: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Accidenttype",
    },
    totalNumberOfPeopleKilled: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Totalnumberofpeoplekilled",
    },
    totalNumberOfPeopleInjured: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Totalnumberofpeopleinjured",
    },
    reasonOrCauseForAccident: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Reasonorcauseforaccident",
    },
    primaryVehicleInvolved: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Primaryvehicleinvolved",
    },
    secondaryVehicleInvolved: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Secondaryvehicleinvolved",
    },
    tertiaryVehicleInvolved: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Tertiaryvehicleinvolved",
    },
    anyMoreVehiclesInvolved: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Anymorevehiclesinvolved",
    },
    availableAgesOfTheDeceased: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Availableagesofthedeceased",
    },
    accidentDatetimeFromUrl: {
      anyOf: [
        {
          type: "string",
          format: "date-time",
        },
        {
          type: "null",
        },
      ],
      title: "Accidentdatetimefromurl",
    },
    accidentDate: {
      anyOf: [
        {
          type: "string",
          format: "date-time",
        },
        {
          type: "null",
        },
      ],
      title: "Accidentdate",
    },
    url: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Url",
    },
    source: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Source",
    },
    accidentIdNumberUrl: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Accidentidnumberurl",
    },
    contentsWholeGptResponse: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Contentswholegptresponse",
    },
    articlesTextFromUrl: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Articlestextfromurl",
    },
    articleTitle: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Articletitle",
    },
    headline: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Headline",
    },
    summary: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Summary",
    },
    duplicateCheck: {
      anyOf: [
        {
          type: "boolean",
        },
        {
          type: "null",
        },
      ],
      title: "Duplicatecheck",
      default: false,
    },
    uId: {
      type: "integer",
      title: "Uid",
    },
  },
  type: "object",
  required: ["uId"],
  title: "AllAccidentsData",
} as const;

export const AllAccidentsDataCreateSchema = {
  properties: {
    news_category: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "News Category",
    },
    id: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Id",
    },
    number_of_accidents_occured: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Number Of Accidents Occured",
    },
    is_the_accident_data_yearly_monthly_or_daily: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Is The Accident Data Yearly Monthly Or Daily",
    },
    day_of_the_week_of_the_accident: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Day Of The Week Of The Accident",
    },
    exact_location_of_accident: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Exact Location Of Accident",
    },
    area_of_accident: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Area Of Accident",
    },
    division_of_accident: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Division Of Accident",
    },
    district_of_accident: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "District Of Accident",
    },
    subdistrict_or_upazila_of_accident: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Subdistrict Or Upazila Of Accident",
    },
    is_place_of_accident_highway_or_expressway_or_water_or_others: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Is Place Of Accident Highway Or Expressway Or Water Or Others",
    },
    is_country_bangladesh_or_other_country: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Is Country Bangladesh Or Other Country",
    },
    accident_type: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Accident Type",
    },
    total_number_of_people_killed: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Total Number Of People Killed",
    },
    total_number_of_people_injured: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Total Number Of People Injured",
    },
    reason_or_cause_for_accident: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Reason Or Cause For Accident",
    },
    primary_vehicle_involved: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Primary Vehicle Involved",
    },
    secondary_vehicle_involved: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Secondary Vehicle Involved",
    },
    tertiary_vehicle_involved: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Tertiary Vehicle Involved",
    },
    any_more_vehicles_involved: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Any More Vehicles Involved",
    },
    available_ages_of_the_deceased: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Available Ages Of The Deceased",
    },
    accident_datetime_from_url: {
      anyOf: [
        {
          type: "string",
          format: "date-time",
        },
        {
          type: "null",
        },
      ],
      title: "Accident Datetime From Url",
    },
    accident_date: {
      anyOf: [
        {
          type: "string",
          format: "date-time",
        },
        {
          type: "null",
        },
      ],
      title: "Accident Date",
    },
    url: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Url",
    },
    source: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Source",
    },
    accident_id_number_url: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Accident Id Number Url",
    },
    contents_whole_gpt_response: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Contents Whole Gpt Response",
    },
    articles_text_from_url: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Articles Text From Url",
    },
    article_title: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Article Title",
    },
    headline: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Headline",
    },
    summary: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Summary",
    },
    duplicate_check: {
      anyOf: [
        {
          type: "boolean",
        },
        {
          type: "null",
        },
      ],
      title: "Duplicate Check",
      default: false,
    },
  },
  type: "object",
  title: "AllAccidentsDataCreate",
} as const;

export const AllAccidentsDataUpdateSchema = {
  properties: {
    news_category: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "News Category",
    },
    id: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Id",
    },
    number_of_accidents_occured: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Number Of Accidents Occured",
    },
    is_the_accident_data_yearly_monthly_or_daily: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Is The Accident Data Yearly Monthly Or Daily",
    },
    day_of_the_week_of_the_accident: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Day Of The Week Of The Accident",
    },
    exact_location_of_accident: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Exact Location Of Accident",
    },
    area_of_accident: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Area Of Accident",
    },
    division_of_accident: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Division Of Accident",
    },
    district_of_accident: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "District Of Accident",
    },
    subdistrict_or_upazila_of_accident: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Subdistrict Or Upazila Of Accident",
    },
    is_place_of_accident_highway_or_expressway_or_water_or_others: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Is Place Of Accident Highway Or Expressway Or Water Or Others",
    },
    is_country_bangladesh_or_other_country: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Is Country Bangladesh Or Other Country",
    },
    accident_type: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Accident Type",
    },
    total_number_of_people_killed: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Total Number Of People Killed",
    },
    total_number_of_people_injured: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Total Number Of People Injured",
    },
    reason_or_cause_for_accident: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Reason Or Cause For Accident",
    },
    primary_vehicle_involved: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Primary Vehicle Involved",
    },
    secondary_vehicle_involved: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Secondary Vehicle Involved",
    },
    tertiary_vehicle_involved: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Tertiary Vehicle Involved",
    },
    any_more_vehicles_involved: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Any More Vehicles Involved",
    },
    available_ages_of_the_deceased: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Available Ages Of The Deceased",
    },
    accident_datetime_from_url: {
      anyOf: [
        {
          type: "string",
          format: "date-time",
        },
        {
          type: "null",
        },
      ],
      title: "Accident Datetime From Url",
    },
    accident_date: {
      anyOf: [
        {
          type: "string",
          format: "date-time",
        },
        {
          type: "null",
        },
      ],
      title: "Accident Date",
    },
    url: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Url",
    },
    source: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Source",
    },
    accident_id_number_url: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Accident Id Number Url",
    },
    contents_whole_gpt_response: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Contents Whole Gpt Response",
    },
    articles_text_from_url: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Articles Text From Url",
    },
    article_title: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Article Title",
    },
    headline: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Headline",
    },
    summary: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Summary",
    },
    duplicate_check: {
      anyOf: [
        {
          type: "boolean",
        },
        {
          type: "null",
        },
      ],
      title: "Duplicate Check",
    },
  },
  type: "object",
  title: "AllAccidentsDataUpdate",
} as const;

export const CommoditySchema = {
  properties: {
    name: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Name",
    },
    bengaliName: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Bengaliname",
    },
    category: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Category",
    },
    unit: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Unit",
    },
    description: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Description",
    },
    imageUrl: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Imageurl",
    },
    id: {
      type: "integer",
      title: "Id",
    },
    createdAt: {
      type: "string",
      format: "date-time",
      title: "Createdat",
    },
    minPrice: {
      anyOf: [
        {
          type: "integer",
        },
        {
          type: "null",
        },
      ],
      title: "Minprice",
    },
    maxPrice: {
      anyOf: [
        {
          type: "integer",
        },
        {
          type: "null",
        },
      ],
      title: "Maxprice",
    },
    currentPrice: {
      anyOf: [
        {
          type: "integer",
        },
        {
          type: "null",
        },
      ],
      title: "Currentprice",
    },
    weeklyChange: {
      anyOf: [
        {
          type: "number",
        },
        {
          type: "null",
        },
      ],
      title: "Weeklychange",
    },
    monthlyChange: {
      anyOf: [
        {
          type: "number",
        },
        {
          type: "null",
        },
      ],
      title: "Monthlychange",
    },
    yearlyChange: {
      anyOf: [
        {
          type: "number",
        },
        {
          type: "null",
        },
      ],
      title: "Yearlychange",
    },
  },
  type: "object",
  required: ["id", "createdAt"],
  title: "Commodity",
} as const;

export const CommodityCreateSchema = {
  properties: {
    name: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Name",
    },
    bengali_name: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Bengali Name",
    },
    category: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Category",
    },
    unit: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Unit",
    },
    description: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Description",
    },
    image_url: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Image Url",
    },
  },
  type: "object",
  title: "CommodityCreate",
} as const;

export const CommodityDetailSchema = {
  properties: {
    name: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Name",
    },
    bengaliName: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Bengaliname",
    },
    category: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Category",
    },
    unit: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Unit",
    },
    description: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Description",
    },
    imageUrl: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Imageurl",
    },
    id: {
      type: "integer",
      title: "Id",
    },
    createdAt: {
      type: "string",
      format: "date-time",
      title: "Createdat",
    },
    minPrice: {
      anyOf: [
        {
          type: "integer",
        },
        {
          type: "null",
        },
      ],
      title: "Minprice",
    },
    maxPrice: {
      anyOf: [
        {
          type: "integer",
        },
        {
          type: "null",
        },
      ],
      title: "Maxprice",
    },
    currentPrice: {
      anyOf: [
        {
          type: "integer",
        },
        {
          type: "null",
        },
      ],
      title: "Currentprice",
    },
    weeklyChange: {
      anyOf: [
        {
          type: "number",
        },
        {
          type: "null",
        },
      ],
      title: "Weeklychange",
    },
    monthlyChange: {
      anyOf: [
        {
          type: "number",
        },
        {
          type: "null",
        },
      ],
      title: "Monthlychange",
    },
    yearlyChange: {
      anyOf: [
        {
          type: "number",
        },
        {
          type: "null",
        },
      ],
      title: "Yearlychange",
    },
    priceHistory: {
      anyOf: [
        {
          items: {
            $ref: "#/components/schemas/PricePoint",
          },
          type: "array",
        },
        {
          type: "null",
        },
      ],
      title: "Pricehistory",
      default: [],
    },
    regionalPrices: {
      anyOf: [
        {
          items: {
            $ref: "#/components/schemas/RegionalPrice",
          },
          type: "array",
        },
        {
          type: "null",
        },
      ],
      title: "Regionalprices",
      default: [],
    },
  },
  type: "object",
  required: ["id", "createdAt"],
  title: "CommodityDetail",
} as const;

export const CommodityInDropdownSchema = {
  properties: {
    id: {
      type: "integer",
      title: "Id",
    },
    name: {
      type: "string",
      title: "Name",
    },
    bengaliName: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Bengaliname",
    },
  },
  type: "object",
  required: ["id", "name"],
  title: "CommodityInDropdown",
} as const;

export const CommodityUpdateSchema = {
  properties: {
    name: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Name",
    },
    bengali_name: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Bengali Name",
    },
    category: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Category",
    },
    unit: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Unit",
    },
    description: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Description",
    },
    image_url: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Image Url",
    },
  },
  type: "object",
  title: "CommodityUpdate",
} as const;

export const HTTPValidationErrorSchema = {
  properties: {
    detail: {
      items: {
        $ref: "#/components/schemas/ValidationError",
      },
      type: "array",
      title: "Detail",
    },
  },
  type: "object",
  title: "HTTPValidationError",
} as const;

export const LocationSchema = {
  properties: {
    name: {
      type: "string",
      title: "Name",
    },
    address: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Address",
      description: "Formatted address of the location",
    },
    latitude: {
      type: "number",
      title: "Latitude",
      description: "Latitude coordinate of the location",
    },
    longitude: {
      type: "number",
      title: "Longitude",
      description: "Longitude coordinate of the location",
    },
    place_id: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Place Id",
      description: "Google Maps Place ID",
    },
    poi_id: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Poi Id",
      description: "Google Maps POI ID",
    },
    id: {
      type: "integer",
      title: "Id",
    },
    created_at: {
      type: "string",
      format: "date-time",
      title: "Created At",
    },
    updated_at: {
      anyOf: [
        {
          type: "string",
          format: "date-time",
        },
        {
          type: "null",
        },
      ],
      title: "Updated At",
    },
  },
  type: "object",
  required: ["name", "latitude", "longitude", "id", "created_at"],
  title: "Location",
} as const;

export const LocationCreateSchema = {
  properties: {
    name: {
      type: "string",
      title: "Name",
    },
    address: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Address",
      description: "Formatted address of the location",
    },
    latitude: {
      type: "number",
      title: "Latitude",
      description: "Latitude coordinate of the location",
    },
    longitude: {
      type: "number",
      title: "Longitude",
      description: "Longitude coordinate of the location",
    },
    place_id: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Place Id",
      description: "Google Maps Place ID",
    },
    poi_id: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Poi Id",
      description: "Google Maps POI ID",
    },
  },
  type: "object",
  required: ["name", "latitude", "longitude"],
  title: "LocationCreate",
} as const;

export const LocationUpdateSchema = {
  properties: {
    name: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Name",
    },
    address: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Address",
      description: "Formatted address of the location",
    },
    latitude: {
      anyOf: [
        {
          type: "number",
        },
        {
          type: "null",
        },
      ],
      title: "Latitude",
    },
    longitude: {
      anyOf: [
        {
          type: "number",
        },
        {
          type: "null",
        },
      ],
      title: "Longitude",
    },
    place_id: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Place Id",
    },
    poi_id: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Poi Id",
    },
  },
  type: "object",
  title: "LocationUpdate",
} as const;

export const PricePointSchema = {
  properties: {
    date: {
      type: "string",
      title: "Date",
    },
    price: {
      type: "integer",
      title: "Price",
    },
  },
  type: "object",
  required: ["date", "price"],
  title: "PricePoint",
} as const;

export const PriceRecordSchema = {
  properties: {
    commodity_id: {
      type: "integer",
      title: "Commodity Id",
    },
    region_id: {
      type: "integer",
      title: "Region Id",
    },
    price: {
      type: "integer",
      title: "Price",
    },
    recorded_by: {
      anyOf: [
        {
          type: "integer",
        },
        {
          type: "null",
        },
      ],
      title: "Recorded By",
    },
    source: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Source",
    },
    source_url: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Source Url",
    },
    notes: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Notes",
    },
    location_id: {
      anyOf: [
        {
          type: "integer",
        },
        {
          type: "null",
        },
      ],
      title: "Location Id",
      description: "ID of the associated location",
    },
    recorded_at: {
      type: "string",
      format: "date",
      title: "Recorded At",
    },
    id: {
      type: "integer",
      title: "Id",
    },
    created_at: {
      type: "string",
      format: "date-time",
      title: "Created At",
    },
    location: {
      anyOf: [
        {
          $ref: "#/components/schemas/Location",
        },
        {
          type: "null",
        },
      ],
    },
  },
  type: "object",
  required: ["commodity_id", "region_id", "price", "recorded_at", "id", "created_at"],
  title: "PriceRecord",
} as const;

export const PriceRecordCreateSchema = {
  properties: {
    commodity_id: {
      type: "integer",
      title: "Commodity Id",
    },
    region_id: {
      type: "integer",
      title: "Region Id",
    },
    price: {
      type: "integer",
      title: "Price",
    },
    recorded_by: {
      anyOf: [
        {
          type: "integer",
        },
        {
          type: "null",
        },
      ],
      title: "Recorded By",
    },
    source: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Source",
    },
    source_url: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Source Url",
    },
    notes: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Notes",
    },
    location_id: {
      anyOf: [
        {
          type: "integer",
        },
        {
          type: "null",
        },
      ],
      title: "Location Id",
      description: "ID of the associated location",
    },
    recorded_at: {
      type: "string",
      format: "date",
      title: "Recorded At",
    },
    location: {
      anyOf: [
        {
          $ref: "#/components/schemas/LocationCreate",
        },
        {
          type: "null",
        },
      ],
      description: "Location details to create",
    },
  },
  type: "object",
  required: ["commodity_id", "region_id", "price", "recorded_at"],
  title: "PriceRecordCreate",
} as const;

export const PriceRecordUpdateSchema = {
  properties: {
    commodity_id: {
      anyOf: [
        {
          type: "integer",
        },
        {
          type: "null",
        },
      ],
      title: "Commodity Id",
    },
    region_id: {
      anyOf: [
        {
          type: "integer",
        },
        {
          type: "null",
        },
      ],
      title: "Region Id",
    },
    price: {
      anyOf: [
        {
          type: "integer",
        },
        {
          type: "null",
        },
      ],
      title: "Price",
    },
    source: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Source",
    },
    notes: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Notes",
    },
    location_id: {
      anyOf: [
        {
          type: "integer",
        },
        {
          type: "null",
        },
      ],
      title: "Location Id",
    },
    recorded_at: {
      anyOf: [
        {
          type: "string",
          format: "date",
        },
        {
          type: "null",
        },
      ],
      title: "Recorded At",
    },
  },
  type: "object",
  title: "PriceRecordUpdate",
} as const;

export const RegionSchema = {
  properties: {
    name: {
      type: "string",
      title: "Name",
    },
    bengali_name: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Bengali Name",
    },
    latitude: {
      type: "number",
      title: "Latitude",
    },
    longitude: {
      type: "number",
      title: "Longitude",
    },
    is_division: {
      type: "boolean",
      title: "Is Division",
      default: true,
    },
    parent_region_id: {
      anyOf: [
        {
          type: "integer",
        },
        {
          type: "null",
        },
      ],
      title: "Parent Region Id",
    },
    id: {
      type: "integer",
      title: "Id",
    },
    created_at: {
      type: "string",
      format: "date-time",
      title: "Created At",
    },
  },
  type: "object",
  required: ["name", "latitude", "longitude", "id", "created_at"],
  title: "Region",
} as const;

export const RegionCreateSchema = {
  properties: {
    name: {
      type: "string",
      title: "Name",
    },
    bengali_name: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Bengali Name",
    },
    latitude: {
      type: "number",
      title: "Latitude",
    },
    longitude: {
      type: "number",
      title: "Longitude",
    },
    is_division: {
      type: "boolean",
      title: "Is Division",
      default: true,
    },
    parent_region_id: {
      anyOf: [
        {
          type: "integer",
        },
        {
          type: "null",
        },
      ],
      title: "Parent Region Id",
    },
  },
  type: "object",
  required: ["name", "latitude", "longitude"],
  title: "RegionCreate",
} as const;

export const RegionalPriceSchema = {
  properties: {
    region: {
      type: "string",
      title: "Region",
    },
    price: {
      type: "integer",
      title: "Price",
    },
    change: {
      type: "integer",
      title: "Change",
    },
  },
  type: "object",
  required: ["region", "price", "change"],
  title: "RegionalPrice",
} as const;

export const UserSchema = {
  properties: {
    email: {
      type: "string",
      format: "email",
      title: "Email",
    },
    username: {
      type: "string",
      title: "Username",
    },
    full_name: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Full Name",
    },
    is_active: {
      type: "boolean",
      title: "Is Active",
      default: true,
    },
    role: {
      type: "string",
      title: "Role",
      default: "viewer",
    },
    id: {
      type: "integer",
      title: "Id",
    },
    created_at: {
      type: "string",
      format: "date-time",
      title: "Created At",
    },
  },
  type: "object",
  required: ["email", "username", "id", "created_at"],
  title: "User",
} as const;

export const UserCreateSchema = {
  properties: {
    email: {
      type: "string",
      format: "email",
      title: "Email",
    },
    username: {
      type: "string",
      title: "Username",
    },
    full_name: {
      anyOf: [
        {
          type: "string",
        },
        {
          type: "null",
        },
      ],
      title: "Full Name",
    },
    is_active: {
      type: "boolean",
      title: "Is Active",
      default: true,
    },
    role: {
      type: "string",
      title: "Role",
      default: "viewer",
    },
    password: {
      type: "string",
      title: "Password",
    },
  },
  type: "object",
  required: ["email", "username", "password"],
  title: "UserCreate",
} as const;

export const ValidationErrorSchema = {
  properties: {
    loc: {
      items: {
        anyOf: [
          {
            type: "string",
          },
          {
            type: "integer",
          },
        ],
      },
      type: "array",
      title: "Location",
    },
    msg: {
      type: "string",
      title: "Message",
    },
    type: {
      type: "string",
      title: "Error Type",
    },
  },
  type: "object",
  required: ["loc", "msg", "type"],
  title: "ValidationError",
} as const;
