"""remove_min_max_price_from_commodity

Revision ID: 041b9276171e
Revises: 83c623dc6903
Create Date: 2025-04-17 13:47:50.098998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '041b9276171e'
down_revision: Union[str, None] = '83c623dc6903'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('commodity', 'max_price')
    op.drop_column('commodity', 'min_price')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('commodity', sa.Column('min_price', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('commodity', sa.Column('max_price', mysql.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ### 