"""drop_supply_chain_tables

Revision ID: 13e93b623d2d
Revises: 041b9276171e
Create Date: 2025-04-19 13:17:59.683223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '13e93b623d2d'
down_revision: Union[str, None] = '041b9276171e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_supplychaindata_id', table_name='supplychaindata')
    op.drop_table('supplychaindata')
    op.drop_table('supplychainstage')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supplychainstage',
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False),
    sa.Column('description', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('order_index', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('supplychaindata',
    sa.Column('commodity_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('stage_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('region_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('price', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('stakeholders', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('location', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('recorded_at', sa.DATE(), nullable=False),
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['commodity_id'], ['commodity.id'], name='supplychaindata_ibfk_1'),
    sa.ForeignKeyConstraint(['region_id'], ['region.id'], name='supplychaindata_ibfk_2'),
    sa.ForeignKeyConstraint(['stage_id'], ['supplychainstage.id'], name='supplychaindata_ibfk_3'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_supplychaindata_id', 'supplychaindata', ['id'], unique=False)
    # ### end Alembic commands ### 