"""add_location_table

Revision ID: 1e4f25f02676
Revises: 25a52ce713af
Create Date: 2025-05-16 23:47:19.380859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1e4f25f02676'
down_revision: Union[str, None] = '25a52ce713af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('place_id', sa.String(length=255), nullable=True),
    sa.Column('poi_id', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_location_id'), 'location', ['id'], unique=False)
    op.create_index(op.f('ix_location_name'), 'location', ['name'], unique=False)
    op.create_index(op.f('ix_location_place_id'), 'location', ['place_id'], unique=False)
    op.add_column('pricerecord', sa.Column('location_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'pricerecord', 'location', ['location_id'], ['id'])
    op.drop_column('pricerecord', 'address')
    op.drop_column('pricerecord', 'name')
    op.drop_column('pricerecord', 'longitude')
    op.drop_column('pricerecord', 'latitude')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pricerecord', sa.Column('latitude', mysql.FLOAT(), nullable=True))
    op.add_column('pricerecord', sa.Column('longitude', mysql.FLOAT(), nullable=True))
    op.add_column('pricerecord', sa.Column('name', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('pricerecord', sa.Column('address', mysql.TEXT(), nullable=True))
    op.drop_constraint(None, 'pricerecord', type_='foreignkey')
    op.drop_column('pricerecord', 'location_id')
    op.drop_index(op.f('ix_location_place_id'), table_name='location')
    op.drop_index(op.f('ix_location_name'), table_name='location')
    op.drop_index(op.f('ix_location_id'), table_name='location')
    op.drop_table('location')
    # ### end Alembic commands ### 