"""add name field to price_record model

Revision ID: 516a822ba6d5
Revises: 13e93b623d2d
Create Date: 2025-04-26 20:18:36.452548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '516a822ba6d5'
down_revision: Union[str, None] = '13e93b623d2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_pricehistoryaggregated_id', table_name='pricehistoryaggregated')
    op.drop_table('pricehistoryaggregated')
    op.add_column('pricerecord', sa.Column('name', sa.String(length=100), nullable=True))
    op.add_column('pricerecord', sa.Column('address', sa.Text(), nullable=True))
    op.add_column('pricerecord', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('pricerecord', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pricerecord', 'longitude')
    op.drop_column('pricerecord', 'latitude')
    op.drop_column('pricerecord', 'address')
    op.drop_column('pricerecord', 'name')
    op.create_table('pricehistoryaggregated',
    sa.Column('commodity_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('region_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('avg_price', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('min_price', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('max_price', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('period', mysql.ENUM('daily', 'weekly', 'monthly', 'quarterly', 'yearly'), nullable=False),
    sa.Column('period_start', sa.DATE(), nullable=False),
    sa.Column('period_end', sa.DATE(), nullable=False),
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.ForeignKeyConstraint(['commodity_id'], ['commodity.id'], name='pricehistoryaggregated_ibfk_1'),
    sa.ForeignKeyConstraint(['region_id'], ['region.id'], name='pricehistoryaggregated_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_pricehistoryaggregated_id', 'pricehistoryaggregated', ['id'], unique=False)
    # ### end Alembic commands ### 