"""add all accident data table

Revision ID: 6d2659360b2d
Revises: c732ee5fa4ff
Create Date: 2025-06-13 20:10:22.318087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d2659360b2d'
down_revision: Union[str, None] = 'c732ee5fa4ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('all_accidents_data',
    sa.Column('u_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('news_category', sa.Text(), nullable=True),
    sa.Column('id', sa.Text(), nullable=True),
    sa.Column('number_of_accidents_occured', sa.Text(), nullable=True),
    sa.Column('is_the_accident_data_yearly_monthly_or_daily', sa.Text(), nullable=True),
    sa.Column('day_of_the_week_of_the_accident', sa.Text(), nullable=True),
    sa.Column('exact_location_of_accident', sa.Text(), nullable=True),
    sa.Column('area_of_accident', sa.Text(), nullable=True),
    sa.Column('division_of_accident', sa.Text(), nullable=True),
    sa.Column('district_of_accident', sa.Text(), nullable=True),
    sa.Column('subdistrict_or_upazila_of_accident', sa.Text(), nullable=True),
    sa.Column('is_place_of_accident_highway_or_expressway_or_water_or_others', sa.Text(), nullable=True),
    sa.Column('is_country_bangladesh_or_other_country', sa.Text(), nullable=True),
    sa.Column('accident_type', sa.Text(), nullable=True),
    sa.Column('total_number_of_people_killed', sa.Text(), nullable=True),
    sa.Column('total_number_of_people_injured', sa.Text(), nullable=True),
    sa.Column('reason_or_cause_for_accident', sa.Text(), nullable=True),
    sa.Column('primary_vehicle_involved', sa.Text(), nullable=True),
    sa.Column('secondary_vehicle_involved', sa.Text(), nullable=True),
    sa.Column('tertiary_vehicle_involved', sa.Text(), nullable=True),
    sa.Column('any_more_vehicles_involved', sa.Text(), nullable=True),
    sa.Column('available_ages_of_the_deceased', sa.Text(), nullable=True),
    sa.Column('accident_datetime_from_url', sa.DateTime(), nullable=True),
    sa.Column('accident_date', sa.DateTime(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('accident_id_number_url', sa.Text(), nullable=True),
    sa.Column('contents_whole_gpt_response', sa.Text(), nullable=True),
    sa.Column('articles_text_from_url', sa.Text(), nullable=True),
    sa.Column('article_title', sa.Text(), nullable=True),
    sa.Column('headline', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('duplicate_check', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('u_id')
    )
    op.create_index(op.f('ix_all_accidents_data_u_id'), 'all_accidents_data', ['u_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_all_accidents_data_u_id'), table_name='all_accidents_data')
    op.drop_table('all_accidents_data')
    # ### end Alembic commands ### 