"""Add accident data table

Revision ID: 7f99fe3a3014
Revises: 6ec5ca3de3de
Create Date: 2025-06-09 21:03:18.701143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f99fe3a3014'
down_revision: Union[str, None] = '6ec5ca3de3de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 