"""add accident data table

Revision ID: c732ee5fa4ff
Revises: 6ec5ca3de3de
Create Date: 2025-06-13 17:10:18.122001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c732ee5fa4ff'
down_revision: Union[str, None] = '6ec5ca3de3de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accident_data_summary',
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('total_accidents', sa.Integer(), nullable=True),
    sa.Column('total_killed', sa.Integer(), nullable=True),
    sa.Column('total_injured', sa.Integer(), nullable=True),
    sa.Column('daily_deaths', sa.Text(), nullable=True),
    sa.Column('daily_injured', sa.Text(), nullable=True),
    sa.Column('monthly_deaths', sa.Text(), nullable=True),
    sa.Column('monthly_injured', sa.Text(), nullable=True),
    sa.Column('accident_hotspot', sa.Text(), nullable=True),
    sa.Column('vehicles_involved', sa.Text(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('accidents_by_district', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accident_data_summary_id'), 'accident_data_summary', ['id'], unique=False)
    op.create_index(op.f('ix_accident_data_summary_year'), 'accident_data_summary', ['year'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_accident_data_summary_year'), table_name='accident_data_summary')
    op.drop_index(op.f('ix_accident_data_summary_id'), table_name='accident_data_summary')
    op.drop_table('accident_data_summary')
    # ### end Alembic commands ### 