"""Add indexes to price_record model

Revision ID: db53a0611bee
Revises: 1e4f25f02676
Create Date: 2025-05-21 21:35:18.330430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db53a0611bee'
down_revision: Union[str, None] = '1e4f25f02676'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_commodity_recorded_at', 'pricerecord', ['commodity_id', 'recorded_at'], unique=False)
    op.create_index('idx_region_recorded_at', 'pricerecord', ['region_id', 'recorded_at'], unique=False)
    op.create_index(op.f('ix_pricerecord_commodity_id'), 'pricerecord', ['commodity_id'], unique=False)
    op.create_index(op.f('ix_pricerecord_recorded_at'), 'pricerecord', ['recorded_at'], unique=False)
    op.create_index(op.f('ix_pricerecord_region_id'), 'pricerecord', ['region_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pricerecord_region_id'), table_name='pricerecord')
    op.drop_index(op.f('ix_pricerecord_recorded_at'), table_name='pricerecord')
    op.drop_index(op.f('ix_pricerecord_commodity_id'), table_name='pricerecord')
    op.drop_index('idx_region_recorded_at', table_name='pricerecord')
    op.drop_index('idx_commodity_recorded_at', table_name='pricerecord')
    # ### end Alembic commands ### 